#!/bin/bash

set -e

TIMESTAMP=`date +%Y%m%d%H%M`
BUILD_VERSION="tpm4-1.0-$TIMESTAMP"

lb build noauto "${@}" 2>&1 | tee build.log
if [ -f live-image-amd64.hybrid.iso ]; then
  mv live-image-amd64.hybrid.iso huayra-tpmtool-$BUILD_VERSION.iso
  md5sum huayra-tpmtool-$BUILD_VERSION.iso > huayra-tpmtool-$BUILD_VERSION.iso.md5
  cp huayra-tpmtool-$BUILD_VERSION.iso* /var/www/html/tpm

else
    echo "#################### ERROR AL GENERAR LA IMANGEN ########################"
fi

