#!/bin/bash

set -e

#BUILD_VERSION=`date +%Y%m%d%H%M`
BUILD_VERSION="tpm2-1.0"

lb build noauto "${@}" 2>&1 | tee build.log
if [ -f live-image-amd64.hybrid.iso ]; then
  mv live-image-amd64.hybrid.iso huayra-tpmtool-$BUILD_VERSION-amd64.iso
  md5sum huayra-tpmtool-$BUILD_VERSION-amd64.iso > huayra-tpmtool-$BUILD_VERSION-amd64.iso.md5
  cp huayra-tpmtool-$BUILD_VERSION-amd64.iso* /var/www/html/tpm

else
    echo "#################### ERROR AL GENERAR LA IMANGEN ########################"
fi

